name: Markdown Web Scraper

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'スクレイピング対象のURL'
        required: true
        default: 'https://example.com'
      max_depth:
        description: '最大深度 (1-5の範囲推奨)'
        required: true
        default: '2'
      use_proxy:
        description: 'CORSプロキシを使用 (true/false)'
        required: false
        default: 'false'
      proxy_url:
        description: 'プロキシURL (例: https://corsproxy.io/?)'
        required: false
        default: 'https://corsproxy.io/?'

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install puppeteer

      - name: Run scraper
        run: |
          # プロキシを使用するかどうかをチェック
          if [ "${{ github.event.inputs.use_proxy }}" == "true" ]; then
            FULL_URL="${{ github.event.inputs.proxy_url }}${{ github.event.inputs.target_url }}"
          else
            FULL_URL="${{ github.event.inputs.target_url }}"
          fi
          
          node web-scraper-markdown.js "$FULL_URL" ${{ github.event.inputs.max_depth }}
        
      - name: Upload scraped data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: scraped-data
          path: scraped_data
          retention-days: 7
